version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=super_secret_warehouse_key_987654321
      - DB_PATH=../database/warehouse.db
      - NODE_ENV=production
    volumes:
      - db-data:/goods-distribution-warehouse-stock-register/database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
